name: Build PS4 Linux Kernel

on:
  workflow_dispatch:

jobs:
  build-linux-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker buildx create --use --driver-opt "env.BUILDKIT_PROGRESS=plain"
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache \
                            --cache-to=type=local,dest=/tmp/.buildx-cache \
                            -t ps4-linux-docker .
        
    - name: Run Docker container to build kernel
      run: |
        docker run --rm -v "$(pwd)/artifacts:/kernel/linux/artifacts" ps4-linux-docker

    - name: Upload bzImage artifact
      uses: actions/upload-artifact@b6a204a6e21d86a9f5a5e4c8c407d7b71ad9e8b0
      with:
        name: bzImage
        path: artifacts/bzImage